spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            clientSecret: 
            scope:
              - email
              - profile
